echo "installing vs-code packages"
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension PeterJausovec.vscode-docker
code --install-extension Rubymaniac.vscode-paste-and-indent
code --install-extension Zignd.html-css-class-completion
code --install-extension alexdima.copy-relative-path
code --install-extension asvetliakov.snapshot-tools
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension formulahendry.auto-rename-tag
code --install-extension foxundermoon.shell-format
code --install-extension jasonnutter.search-node-modules
code --install-extension jawandarajbir.react-vscode-extension-pack
code --install-extension mrmlnc.vscode-autoprefixer
code --install-extension naumovs.color-highlight
code --install-extension pranaygp.vscode-css-peek
code --install-extension raphx.stylelint
code --install-extension robertohuertasm.vscode-icons
code --install-extension Shan.code-settings-sync
code --install-extension sleistner.vscode-fileutils
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets