export const SEARCH_CHORDS = 'SEARCH_CHORDS';
export const SET_CHORD_SEARCH_RESULTS = 'SET_CHORD_SEARCH_RESULTS';
export const CHORD_CLICKED = 'CHORD_CLICKED';
export const CLEAR_CHORD_SEARCH = 'CLEAR_CHORD_SEARCH';
